endpoint:
  verificationRequestExpiresIn: PT5M
  ageThresholds:
    crackle: [13, 18]
    pop: [13, 18]

clients:
  sites:
    urls:
      crackle: http://crackle
      pop: http://pop
  dynamoDb:
    region: us-east-1
    testEndpointOverride: http://checkmyage-dynamodb:8000
  redis:
    uri: http://checkmyage-redis:6379

keys:
  signing:
    s: 87808632867103956881705523559918117434194472117688001288631494927155518459976
  localization:
    keys:
      crackle: pER-dDPdsvdvcP9szpckd6GHHc1qg44Rt70LTUqHTpY
      pop: W1zah29NMWEOEsd8VNFX6E3Vo8Z-HLNQ5cDH3-9KyVg

server:
  applicationConnectors:
    - type: http
      port: 80
  adminConnectors: []
